version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: tintoreria
    container_name: tintoreria-app
    restart: unless-stopped
    working_dir: /var/www/
    depends_on:
      - db
      - redis
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - tintoreria

  db:
    image: mysql:8.0
    container_name: tintoreria-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tintoreria
      MYSQL_ROOT_PASSWORD: tintoreria
      MYSQL_PASSWORD: tintoreria
      MYSQL_USER: tintoreria
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - tintoreria

  nginx:
    image: nginx:alpine
    container_name: tintoreria-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - tintoreria

  redis:
    image: redis:alpine
    container_name: tintoreria-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - tintoreria
    volumes:
      - redisdata:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tintoreria-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: tintoreria
    networks:
      - tintoreria

networks:
  tintoreria:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local 