services:
  - type: web
    name: tintoreria
    env: docker
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tintoreria-db
          property: connectionString
      - key: APP_URL
        value: https://tintoreria.onrender.com

databases:
  - name: tintoreria-db
    ipAllowList: []
